package com.cox.cox;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class IssueTypeDO implements java.io.Serializable {

    static final long serialVersionUID = 1L;

	private java.lang.String tIssueType;

	public IssueTypeDO() {
	}

	public java.lang.String gettIssueType() {
		return this.tIssueType;
	}

	public void settIssueType(java.lang.String tIssueType) {
		this.tIssueType = tIssueType;
	}

	public IssueTypeDO(java.lang.String tIssueType) {
		this.tIssueType = tIssueType;
	}

}